config/routes.rb
Pwdapp::Application.routes.draw do
  resources :location_groups

  resources :locations

  resources :notifications

  resources :user_locations

  devise_for :users
  
  get  'welcome' => 'pages#welcome'
  
  get  'settings' => 'settings#edit'
  post 'settings' => 'settings#update', :as => 'update_settings'
  
  get  'requests/:id/new' => 'requests#new', :as => 'new_request'
  post 'requests/:id' => 'requests#create', :as => 'create_request'
  post 'requests' => 'requests#update', :as => 'update_requests'
  

  root :to => 'pages#index'

end

app/models/location_group.rb
class LocationGroup < ActiveRecord::Base
  attr_accessible :name, :order
end

app/controllers/location_groups_controller.rb
class LocationGroupsController < ApplicationController
  # GET /location_groups
  # GET /location_groups.json
  def index
    @location_groups = LocationGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @location_groups }
    end
  end

  # GET /location_groups/1
  # GET /location_groups/1.json
  def show
    @location_group = LocationGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location_group }
    end
  end

  # GET /location_groups/new
  # GET /location_groups/new.json
  def new
    @location_group = LocationGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location_group }
    end
  end

  # GET /location_groups/1/edit
  def edit
    @location_group = LocationGroup.find(params[:id])
  end

  # POST /location_groups
  # POST /location_groups.json
  def create
    @location_group = LocationGroup.new(params[:location_group])

    respond_to do |format|
      if @location_group.save
        format.html { redirect_to @location_group, notice: 'Location group was successfully created.' }
        format.json { render json: @location_group, status: :created, location: @location_group }
      else
        format.html { render action: "new" }
        format.json { render json: @location_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /location_groups/1
  # PUT /location_groups/1.json
  def update
    @location_group = LocationGroup.find(params[:id])

    respond_to do |format|
      if @location_group.update_attributes(params[:location_group])
        format.html { redirect_to @location_group, notice: 'Location group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_groups/1
  # DELETE /location_groups/1.json
  def destroy
    @location_group = LocationGroup.find(params[:id])
    @location_group.destroy

    respond_to do |format|
      format.html { redirect_to location_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/location_groups_helper.rb
module LocationGroupsHelper
end

app/views/location_groups/_form.html.erb
<%= form_for(@location_group) do |f| %>
  <% if @location_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location_group.errors.count, "error") %> prohibited this location_group from being saved:</h2>

      <ul>
      <% @location_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/location_groups/edit.html.erb
<h1>Editing location_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @location_group %> |
<%= link_to 'Back', location_groups_path %>

app/views/location_groups/index.html.erb
<h1>Listing location_groups</h1>

<table>
  <tr>
    <th>Order</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @location_groups.each do |location_group| %>
  <tr>
    <td><%= location_group.order %></td>
    <td><%= location_group.name %></td>
    <td><%= link_to 'Show', location_group %></td>
    <td><%= link_to 'Edit', edit_location_group_path(location_group) %></td>
    <td><%= link_to 'Destroy', location_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location group', new_location_group_path %>

app/views/location_groups/new.html.erb
<h1>New location_group</h1>

<%= render 'form' %>

<%= link_to 'Back', location_groups_path %>

app/views/location_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order:</b>
  <%= @location_group.order %>
</p>

<p>
  <b>Name:</b>
  <%= @location_group.name %>
</p>


<%= link_to 'Edit', edit_location_group_path(@location_group) %> |
<%= link_to 'Back', location_groups_path %>