config/routes.rb
Pwdapp::Application.routes.draw do
  resources :location_groups

  resources :locations

  resources :notifications

  resources :user_locations

  devise_for :users
  
  get  'welcome' => 'pages#welcome'
  
  get  'settings' => 'settings#edit'
  post 'settings' => 'settings#update', :as => 'update_settings'
  
  get  'requests/:id/new' => 'requests#new', :as => 'new_request'
  post 'requests/:id' => 'requests#create', :as => 'create_request'
  post 'requests' => 'requests#update', :as => 'update_requests'
  

  root :to => 'pages#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :message, :user_id
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.user_id %></td>
    <td><%= notification.message %></td>
    <td><%= link_to 'Show', notification %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @notification.user_id %>
</p>

<p>
  <b>Message:</b>
  <%= @notification.message %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>