config/routes.rb
Pwdapp::Application.routes.draw do
  resources :location_groups

  resources :locations

  resources :notifications

  resources :user_locations

  devise_for :users
  
  get  'welcome' => 'pages#welcome'
  
  get  'settings' => 'settings#edit'
  post 'settings' => 'settings#update', :as => 'update_settings'
  
  get  'requests/:id/new' => 'requests#new', :as => 'new_request'
  post 'requests/:id' => 'requests#create', :as => 'create_request'
  post 'requests' => 'requests#update', :as => 'update_requests'
  

  root :to => 'pages#index'

end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  attr_accessible :location_id, :login_name, :user_id
  
  belongs_to :user
  belongs_to :location
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
  # GET /user_locations
  # GET /user_locations.json
  def index
    @user_locations = UserLocation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_locations }
    end
  end

  # GET /user_locations/1
  # GET /user_locations/1.json
  def show
    @user_location = UserLocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_location }
    end
  end

  # GET /user_locations/new
  # GET /user_locations/new.json
  def new
    @user_location = UserLocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_location }
    end
  end

  # GET /user_locations/1/edit
  def edit
    @user_location = UserLocation.find(params[:id])
  end

  # POST /user_locations
  # POST /user_locations.json
  def create
    @user_location = UserLocation.new(params[:user_location])

    respond_to do |format|
      if @user_location.save
        format.html { redirect_to @user_location, notice: 'User location was successfully created.' }
        format.json { render json: @user_location, status: :created, location: @user_location }
      else
        format.html { render action: "new" }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_locations/1
  # PUT /user_locations/1.json
  def update
    @user_location = UserLocation.find(params[:id])

    respond_to do |format|
      if @user_location.update_attributes(params[:user_location])
        format.html { redirect_to @user_location, notice: 'User location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_locations/1
  # DELETE /user_locations/1.json
  def destroy
    @user_location = UserLocation.find(params[:id])
    @user_location.destroy

    respond_to do |format|
      format.html { redirect_to user_locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/views/user_locations/_form.html.erb
<%= form_for(@user_location) do |f| %>
  <% if @user_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_location.errors.count, "error") %> prohibited this user_location from being saved:</h2>

      <ul>
      <% @user_location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :login_name %><br />
    <%= f.text_field :login_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_locations/edit.html.erb
<h1>Editing user_location</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_location %> |
<%= link_to 'Back', user_locations_path %>

app/views/user_locations/index.html.erb
<h1>Listing user_locations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Location</th>
    <th>Login name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_locations.each do |user_location| %>
  <tr>
    <td><%= user_location.user_id %></td>
    <td><%= user_location.location_id %></td>
    <td><%= user_location.login_name %></td>
    <td><%= link_to 'Show', user_location %></td>
    <td><%= link_to 'Edit', edit_user_location_path(user_location) %></td>
    <td><%= link_to 'Destroy', user_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User location', new_user_location_path %>

app/views/user_locations/new.html.erb
<h1>New user_location</h1>

<%= render 'form' %>

<%= link_to 'Back', user_locations_path %>

app/views/user_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_location.user_id %>
</p>

<p>
  <b>Location:</b>
  <%= @user_location.location_id %>
</p>

<p>
  <b>Login name:</b>
  <%= @user_location.login_name %>
</p>


<%= link_to 'Edit', edit_user_location_path(@user_location) %> |
<%= link_to 'Back', user_locations_path %>