config/routes.rb
Pwdapp::Application.routes.draw do
  resources :location_groups

  resources :locations

  resources :notifications

  resources :user_locations

  devise_for :users
  
  get  'welcome' => 'pages#welcome'
  
  get  'settings' => 'settings#edit'
  post 'settings' => 'settings#update', :as => 'update_settings'
  
  get  'requests/:id/new' => 'requests#new', :as => 'new_request'
  post 'requests/:id' => 'requests#create', :as => 'create_request'
  post 'requests' => 'requests#update', :as => 'update_requests'
  

  root :to => 'pages#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :badge, :location_group_id, :name
  
  has_many :user_locations
  has_one :location_group
  
  scope :not_in_user_locations, lambda { |user| { :conditions => ['locations.id NOT IN (SELECT locations.id FROM locations JOIN user_locations ON user_locations.location_id = locations.id WHERE user_locations.user_id = ?)', user.id] }}
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :badge %><br />
    <%= f.text_field :badge %>
  </div>
  <div class="field">
    <%= f.label :location_group_id %><br />
    <%= f.number_field :location_group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Badge</th>
    <th>Location group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.badge %></td>
    <td><%= location.location_group_id %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Badge:</b>
  <%= @location.badge %>
</p>

<p>
  <b>Location group:</b>
  <%= @location.location_group_id %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>